# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Grade', models.CharField(max_length=4)),
                ('Experience', models.TextField()),
                ('Guardian', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
                ('Class', models.CharField(max_length=50)),
            ],
        ),
    ]
